### ISSUE TITLE
Docker speed

### ISSUE THREAD

**Issue by jripmeester** [nystudio107/craft#57]
### Question
Hi Andrew,

We're using this docker / webpack setup for a few projects now. We're loving it and it's a great base to start off with. But Docker speed on Mac os is killing us. Loading a image heavy page sometimes takes minutes. We know Docker for mac is slow so it's definitly not your project.

I've tried NFS, sync solutions and even a rebuild of this package to nitro but all attempts failed. That might just be my lack of experience.

So i was wondering how do you handle this?  Or don't you experience any slow processes?

Thanks!

**Comment by khalwat** [comment]
So... I'm not sure what to say, except that I think something else might be wrong.

I'm not experiencing the extreme slowness that you're noting. If loading an image-heavy page takes a long time, that sounds more to me like some kind of a DNS issue (unless image transforms are being done).

You should not be experiencing the slowness you're describing. Try this, spin up this project locally:

https://github.com/nystudio107/devmode#try-devmodefm-yourself

...and after it's all loaded up (it'll be slow to build the images initially), tell me what the speed is like. Because this is what it's like here:

https://twitter.com/nystudio107/status/1359578091828486150?s=20

**Comment by jripmeester** [comment]
@khalwat 

Thanks for your quick repsonse.

I'm talking about local dev and it's the image transforms (we use imager-x) that are most time consuming. But all over local performance is lacking.

Our docker resources are set to 4 cpu's, 8 GB mem and 2gb swap. 
I'm on a 2019 macbook pro 2,6 GHz 6-Core Intel Core i7 with Big Sur.

Tried your devmode images. Spinning the whole thing up took 15 minutes. 
Navigating from dashboard to entries overview in CMS takes 482 ms
Loading homepage takes: 1,425 ms

Is that what we might expect?

**Comment by khalwat** [comment]
> Tried your devmode images. Spinning the whole thing up took 15 minutes.
> Navigating from dashboard to entries overview in CMS takes 482 ms
> Loading homepage takes: 1,425 ms

Sounds a bit slower than I'd expect -- if I had to guess, probably your machine is paging. How much RAM total do you have in it?

You shouldn't need a whole lot of swap allocated to Docker unless it's starved for resources, and 8GB is anything but starved.

That said, image transforms can be intensive -- there's also our ImageOptimize plugin as well: https://nystudio107.com/plugins/imageoptimize
