### ISSUE TITLE
Docker container names still use underscore; `up` conditional always fails

### ISSUE THREAD

**Issue by ryanirelan** [nystudio107/craft#72]
### Describe the bug
After the [change to the Makefile to use hyphens in the container names instead of underscores](https://github.com/nystudio107/craft/commit/faee961c3509f564b3cbdb67c4885eaf0d4ef2a8), the conditional in the`up` command in the make file always evaluates false. The result is running something like `make craft migrate/up` shuts down the existing containers and spins up new ones.

I'm only working in the `craft-vite` branch currently. I haven't tested in other branches.

### To reproduce
1. Create a new Craft project per the README instructions. 
2. With the containers runnings, open a new terminal window and run `make craft`
3. See that the conditional evaluates to false and new containers spin up. 

### Expected behavior
I expect that the conditional would find the containers that are already running and run the `craft` command against them.

### Screenshots
<img width="536" alt="Screen Shot 2021-11-10 at 8 47 43 AM" src="https://user-images.githubusercontent.com/2238/141134819-a10cc65a-0050-492a-950e-a402636c328a.png">

<img width="964" alt="Screen Shot 2021-11-10 at 8 50 00 AM" src="https://user-images.githubusercontent.com/2238/141135223-fd67f239-8e41-4ea6-a3bb-e9e432affd84.png">

### Versions
- Latest version of this repository in the `craft-vite` branch
- Docker Desktop 4.2.0 (runs Docker Engine 20.10.10)

**Comment by khalwat** [comment]
It looks like they changed it back, which is... annoying to say the least :)

**Comment by khalwat** [comment]
So this ends up being that they initially switched it to use the Docker Compose v2 (which uses `-`'s`) and then switched _back_ to Docker Compose v1 (which uses `_`'s`). 

But it's now a _preference_ in Docker desktop to turn on Docker Composer v2. So this can be fixed with a Docker preference setting:

![pgunC](https://user-images.githubusercontent.com/7570798/141183875-9d310e8e-1468-4936-b6b8-bcb97fcec3c2.png)

Enable: **Use Docker Compose V2** -- more here: https://docs.docker.com/compose/cli-command/
